# permissions for end users to view postgres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgres-viewer-role
rules:
- apiGroups:
  - db.pandarocks.com
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.pandarocks.com
  resources:
  - postgres/status
  verbs:
  - get
